version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /emscripten/npm
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /bindings/java
    schedule:
      interval: daily
