name: Check clang-format
on: [push, pull_request]
jobs:
  formatting-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: "include"
            exclude: "(hum|crc|midi|json|pugi|utf8|win32|zip)"
          - check: "src"
            exclude: "(hum|crc|midi|json|pugi)"
          - check: "libmei/addons"
          - check: "tools"
    
    name: Check for ${{ matrix.path['check'] }}
          
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@f62da5e3d3a2d88ff364771d9d938773a618ab5e # v4.11.0
        with:
          clang-format-version: "18"
          check-path: ${{ matrix.path['check'] }}
          exclude-regex: ${{ matrix.path['exclude'] }}
